// <auto-generated />
using System;
using DAL.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ParkerCharityContext))]
    [Migration("20230305171838_mGenGroup-v03")]
    partial class mGenGroupv03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.DataBase.EptQuestionList", b =>
                {
                    b.Property<int>("x_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("x_"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<bool?>("BeforeYouHaveJob")
                        .HasColumnType("bit");

                    b.Property<bool?>("DoYouWantHaveJob")
                        .HasColumnType("bit");

                    b.Property<bool?>("HaveSkill")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("S01")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S02")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S03")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S04")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S05")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S06")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S07")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S08")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S09")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S10")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S11")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S12")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S13")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S14")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S15")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S16")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S17")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S18")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S19")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S20")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S21")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S22")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S23")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S24")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S25")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S26")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S27")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S28")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S29")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S30")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S31")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S32")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S33")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S34")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S35")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S36")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S37")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S38")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S39")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S40")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S41")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S42")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S43")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S44")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S45")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S46")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S47")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S48")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S49")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S50")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S51")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S52")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S53")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S54")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S55")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S56")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S57")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S58")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S59")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S60")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S61")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S62")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S63")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S64")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S65")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S66")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S67")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S68")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S69")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S70")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S71")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S72")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S73")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S74")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S75")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S76")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S77")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S78")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S79")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S80")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S81")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S82")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S83")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S84")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S85")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S86")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S87")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S88")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S89")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S90")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S91")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S92")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S93")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S94")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S95")
                        .HasColumnType("tinyint");

                    b.Property<string>("xFamily")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("xName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("x_");

                    b.ToTable("EptQuestion");
                });

            modelBuilder.Entity("DAL.DataBase.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DAL.DataBase.mGenGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("mGenGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
